---
- name: Configure VM for running Bwb workflows
  hosts: all

  roles:
    - {role: docker, become: yes, docker_install_compose: no}
    - bwb-setup

  tasks:
  - ansible.builtin.include_tasks:
      file: dist-upgrade.yml
  - name: Set color prompt
    ansible.builtin.shell:
      cmd: "sed -i 's/^#force_color_prompt/force_color_prompt/' {{ ansible_user_dir }}/.bashrc"
  - name: Case-insensitive tab complete
    ansible.builtin.shell:
      cmd: "echo 'set completion-ignore-case on' > {{ ansible_user_dir }}/.inputrc"
