---
- name: Copy BioDepot specific setup scripts.
  ansible.builtin.copy:
    src: "{{ role_path }}/files/"
    dest: "{{ ansible_user_dir }}/"
    mode: 0775
- name: Setup alias for Bwb.
  ansible.builtin.shell:
    cmd: "echo 'alias bwb={{ ansible_user_dir }}/start_bwb.sh' > {{ ansible_user_dir }}/.bash_aliases"
